// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using productcart.Context;

#nullable disable

namespace productcart.Migrations
{
    [DbContext(typeof(productcontext))]
    [Migration("20260613215650_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("productcart.Entity.order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int")
                        .HasColumnName("invoicenumber");

                    b.Property<string>("InvoiceSequence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("invoicesequence");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("ordernumber");

                    b.Property<float>("OrderPrice")
                        .HasColumnType("real")
                        .HasColumnName("orderprice");

                    b.Property<string>("OrderSequence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ordersequence");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int")
                        .HasColumnName("orderstatus");

                    b.Property<float>("OrderTax")
                        .HasColumnType("real")
                        .HasColumnName("ordertax");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("order");
                });

            modelBuilder.Entity("productcart.Entity.product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("productname");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real")
                        .HasColumnName("productprice");

                    b.HasKey("Id");

                    b.ToTable("product");
                });

            modelBuilder.Entity("productcart.Entity.user", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobilenumber");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("productcart.Entity.order", b =>
                {
                    b.HasOne("productcart.Entity.product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("productcart.Entity.user", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
